@startuml FileFolderClassDiagram

class FileFolder {
    -folders : HashMap<String, ArrayList<Passenger>>
    +FileFolder()
    +addFile(newPassenger : Passenger) : void
    +getFile(passengerName : String, flightNumber : int, seatClass : Flight.SeatClass, seatNumber : int, isWaitListed : boolean) : Passenger
    +getFiles(firstName : String, lastName : String) : String[]
    +removeFile(passengerName : String, flightNumber : int, seatClass : Flight.SeatClass, seatNumber : int, isWaitListed : boolean) : void
    -insertionSortFolder(folder : ArrayList<Passenger>) : void
    -searchFolder(folder : ArrayList<Passenger>, passengerName : String, flightNumber : int, seatClass : Flight.SeatClass, seatNumber : int, isWaitListed : boolean) : Passenger
    -binarySearchFolder(folder : ArrayList<Passenger>, firstName : String, lastName : String) : ArrayList<Passenger>
    -searchFolderRemoveFile(folder : ArrayList<Passenger>, passengerName : String, flightNumber : int, seatClass : Flight.SeatClass, seatNumber : int, isWaitListed : boolean) : void
}

class Passenger {
    -firstName : String
    -lastName : String
    -passportNumber : String
    -flightNumber : int
    -seatClass : Flight.SeatClass
    -seatWaitNumber : int
    -isWaitListed : boolean
    +getFullName() : String
    +getFirstName() : String
    +getLastName() : String
    +getPassport() : String
    +getFlightNumber() : int
    +getSeatClass() : Flight.SeatClass
    +getSeatWaitNumber() : int
    +getIsWaitListed() : boolean
}

FileFolder "1" -- "*" Passenger : contains

@enduml

