@startuml
actor User
participant "Flight" as Flight
participant "Queue" as WaitList

User -> Flight : removePassengerFromWait(seatClass, waitNumber)
activate Flight

Flight -> WaitList : getWait(seatClass)
activate WaitList
WaitList -> WaitList : popItem(waitNumber - 1)
WaitList --> Flight
deactivate WaitList

Flight --> User : void
deactivate Flight
@enduml
