@startuml
actor User
participant "Main" as M
participant "FileFolder" as FF

User -> M : selectPassengerFromComboBox()
activate M
M -> FF : getFile(passengerName)
activate FF
FF --> M : Passenger
deactivate FF
M --> User : displayPassengerDetails()
deactivate M
@enduml



