@startuml
actor User
participant "Main" as M
participant "Flight" as F
participant "FileFolder" as FF
participant "Passenger" as P

User -> M : schedPassButtonActionPerformed()
activate M

M -> F : getFlight(selectedFlightIndex)
activate F
F --> M : Flight
deactivate F

M -> F : checkAvailableSeats()
activate F
F --> M : availableSeats
deactivate F

alt if availableSeats is not empty
    M -> User : showAvailableSeatsDialog(availableSeats)
    User -> M : selectedSeat
    M -> F : addPassengerToSeat(selectedSeat)
    activate F
    F --> M
    deactivate F
    M -> P : new Passenger(details)
    activate P
    P --> M : Passenger
    deactivate P
    M -> FF : addFile(Passenger)
    activate FF
    FF --> M
    deactivate FF
else
    M -> F : checkWaitList()
    activate F
    F --> M : waitListStatus
    deactivate F

    alt if waitListStatus is not full
        M -> User : showWaitListDialog()
        User -> M : userDecision
        alt if userDecision is Yes
            M -> F : addPassengerToWaitList()
            activate F
            F --> M
            deactivate F
            M -> P : new Passenger(details)
            activate P
            P --> M : Passenger
            deactivate P
            M -> FF : addFile(Passenger)
            activate FF
            FF --> M
            deactivate FF
        else
            M --> User : noActionTaken()
        end
    else
        M -> User : showFullWaitListMessage()
    end
end

M --> User : updateUI()
deactivate M
@enduml


