@startuml
actor User
participant "Main" as M
participant "FileFolder" as FF

User -> M : seatsComboBoxActionPerformed()
activate M
M -> FF : getFile(passengerName)
activate FF
FF --> M : Passenger
deactivate FF
M -> M : updatePassengerDetails(Passenger)
M --> User : displayPassengerDetails()
deactivate M
@enduml



