@startuml
actor User
participant "Main" as M
participant "Flight" as F

User -> M : selectFlightFromList()
activate M
M -> F : getFlightInfo(selectedFlightIndex)
activate F
F --> M : flightInfo
deactivate F
M --> User : displayFlightInfo()
deactivate M
@enduml


