@startuml
actor User
participant "Main" as M
participant "Flight" as F
participant "FileFolder" as FF

User -> M : cancelPassButtonActionPerformed()
activate M

M -> F : getFlight(selectedIndex)
activate F
F --> M : selectedFlight
M -> F : selectedFlight.removePassenger(seatNumber)
deactivate F

M -> FF : removeFile(passenger)
activate FF
FF --> M
deactivate FF

' Check if there is a passenger on the waitlist
M -> F : selectedFlight.checkWaitList()
activate F
F --> M : waitListStatus
deactivate F
M -> User : showDialog("Move passenger from waitlist?")
User --> M : userDecision

alt if userDecision is Yes
    M -> F : selectedFlight.movePassengerFromWaitToSeat()
    activate F
    F --> M
    deactivate F
    M -> FF : updatePassengerFile(seatNumber, isWaitListed)
    activate FF
    FF --> M
    deactivate FF
else
    M -> M : updateUI()
end

M --> User : displayUpdatedInfo()
deactivate M
@enduml

